import { DailyStep } from './DailyStep.js';

const currentDate = new Date();
const dayNum = currentDate.getDay();

// Initialize Days
const day0 = createDailyStep0();
const day1 = createDailyStep1();
const day2 = createDailyStep2();
const day3 = createDailyStep3();
const day4 = createDailyStep4();
const day5 = createDailyStep5();
const day6 = createDailyStep6();

const dayArr = [day0, day1, day2, day3, day4, day5, day6];

document.getElementById('challengeText').textContent = dayArr[dayNum].getStep();
document.getElementById('fact1Text').textContent = dayArr[dayNum].getFact1();
document.getElementById('fact2Text').textContent = dayArr[dayNum].getFact2();
document.getElementById('fact3Text').textContent = dayArr[dayNum].getFact3();
const imageElement = document.getElementById("stepImage");
imageElement.src = dayArr[dayNum].getImage();

function createDailyStep0()
{
  const step = "Don't throw away any food today! Idea: If you have bananas that have gone bad, make banana bread!";
  const fact1 = "40% of all food in the United States is wasted.";
  const fact2 = "135 million tons of GHG emissions are created by the food we never eat";
  const fact3 = "One third of all food produced is lost or wasted – costing the global economy close to $940 billion each year.";
  const image = "croppedFoodWaste.png";
  return new DailyStep(step, fact1, fact2, fact3, image);
}

function createDailyStep1()
{
  const step = "Donate a piece of clothing you no longer wear or make it into something you love! Idea: Cut off sleeves from a t-shirt you like but no longer fits and make it into a tank top!";
  const fact1 = "The equivalent of one garbage truck full of clothes is burned or dumped in a landfill every second.";
  const fact2 = "Approximately 60% of all materials used by the fashion industry are made from plastic.";
  const fact3 = "2.5 tonnes of carbon dioxide is generated by producing 1 tonne of plastic.";
  const image = "plastic.png";
  return new DailyStep(step, fact1, fact2, fact3, image);
}

function createDailyStep2()
{
  const step = "Don’t buy any plastic today!";
  const fact1 = "The top 3 most commonly found plastic items in freshwater enviornments are plastic bottles, food wrappers, and takeout containers.";
  const fact2 = "90% of plastic is made from fossil fuels.";
  const fact3 = "2.5 tonnes of carbon dioxide is generated by producing 1 tonne of plastic.";
  const image = "plastic.png";
  return new DailyStep(step, fact1, fact2, fact3, image);
}

function createDailyStep3()
{
  const step = "Don’t buy any plastic today!";
  const fact1 = "The top 3 most commonly found plastic items in freshwater enviornments are plastic bottles, food wrappers, and takeout containers.";
  const fact2 = "90% of plastic is made from fossil fuels.";
  const fact3 = "2.5 tonnes of carbon dioxide is generated by producing 1 tonne of plastic.";
  const image = "plastic.png";
  return new DailyStep(step, fact1, fact2, fact3, image);
}

function createDailyStep4()
{
  const step = "Don’t buy any plastic today!";
  const fact1 = "sdjhfkjsdhkfjhsxdkjfhskdhj";
  const fact2 = "lkaslalalalalalalallalalala";
  const fact3 = "akkakakakakakakakakakakakka";
  const image = "croppedFoodWaste.png";
  return new DailyStep(step, fact1, fact2, fact3, image);
}

function createDailyStep5()
{
  const step = "Don’t buy any plastic today!";
  const fact1 = "sdjhfkjsdhkfjhsxdkjfhskdhj";
  const fact2 = "lkaslalalalalalalallalalala";
  const fact3 = "akkakakakakakakakakakakakka";
  const image = "croppedFoodWaste.png";
  return new DailyStep(step, fact1, fact2, fact3, image);
}

function createDailyStep6()
{
  const step = "Don’t buy any plastic today!";
  const fact1 = "sdjhfkjsdhkfjhsxdkjfhskdhj";
  const fact2 = "lkaslalalalalalalallalalala";
  const fact3 = "akkakakakakakakakakakakakka";
  const image = "croppedFoodWaste.PNG";
  return new DailyStep(step, fact1, fact2, fact3, image);
}

